### PR TITLE
Updated to use latest Docker v1.11.0 and Volume API

### PR DESCRIPTION
**Pull request by clintkitson**
This commit updates the volume API implementation to leverage
the Docker v1.11.0. There was an addition of Get() and List()
methods in prior v1.10. The Get() method now replaces the
call that implicitly created volumes. The Create() method
was used for Path() and other methods prior because there
was no Get() method that returned a volume object.

### CODE REVIEW

**Comment by clintonskitson** [comment]
```

**Comment by clintkitson** [comment]
```
root@mesos-master:/home/vagrant# ./dvdcli --volumedriver=rexray --volumename=test45 mount --explicitcreate=true
ERRO[0000] VolumeDriver.Get: {"Error":"No volumes returned"}
  volumeName=test45
root@mesos-master:/home/vagrant# ./dvdcli --volumedriver=rexray --volumename=test45 mount --explicitcreate=false
INFO[0012] /var/lib/rexray/volumes/test45/data          
/var/lib/rexray/volumes/test45/data
```

**Comment by clintkitson** [comment]
The default behavior is the same as behavior, except there is no longer a create volume called in any case for Unmount() or Path(), a Get() is done instead to verify the volume exists or not. @cantbewong Can you verify that the mesos-module-dvdi will not be adversely affected if we error on missing volumes for Unmount() and Path() now? 

The Mount() method now inherently is implict as before. But there is a specific flag to set it as explicit by `--explicitcreate=true`.

**Comment by gyliu513** [comment]
@clintonskitson when do you plan have this released? Can you please cut a branch and create a new release for it? Thanks.

**Comment by clintkitson** [comment]
@jay-lau Have you had a chance to test and verify?

**Comment by clintkitson** [comment]
@jay-lau 

```
curl -sSL https://dl.bintray.com/emccode/dvdcli/install | sh -s staged
```

```
root@mesos-master:/home/vagrant# dvdcli --volumedriver=docker --volumename=test111123 mount --explicitcreate=true
ERRO[0000] VolumeDriver.Get: {"Error":"No volumes returned"}
  volumeName=test111123
root@mesos-master:/home/vagrant# dvdcli --volumedriver=docker --volumename=test111123 mount --explicitcreate=false
INFO[0000] /var/lib/rexray/volumes/test111123/data      
/var/lib/rexray/volumes/test111123/data
```

**Comment by gyliu513** [comment]
@clintonskitson when do you want to have a stable version of 0.2.0? I saw that current version is 0.2.0-rc1

```
root@mesos002:~/src/mesos/m2/mesos/build# dvdcli version
Binary: /usr/bin/dvdcli
SemVer: 0.2.0-rc1
OsArch: Linux-x86_64
Branch: v0.2.0-rc1
Commit: a789d3ddde4fa9ce3201e3f7bd5ca0cec10a9132
Formed: Tue, 19 Apr 2016 03:55:17 CST
```

**Comment by clintkitson** [comment]
Planning on it today.

**Comment by clintkitson** [comment]
@jay-lau https://github.com/emccode/dvdcli/releases/tag/v0.2.0

**Comment by gyliu513** [comment]
Cool! Thanks @clintonskitson

**Pull request merged**
